# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    only:
      - /feature\/.*/
    docker:
      - image: salesforce/salesforcedx:7.50.0-full
    steps:
      - checkout
      - run:
          name: Run Static Analysis
          command: |
            ./build/static-analysis/run-analysis.sh
    steps:
      - checkout
      - run:
          name: Build and Run Tests
          command: |
            ./build/sfdx/login.sh -l https://login.salesforce.com -c $SFDC_CLIENT_ID -u $SFDC_USER
            ./build/sfdx/run-tests.sh
  package:
    only:
      - master
    docker:
      - image: salesforce/salesforcedx:7.50.0-full
    steps:
      - checkout
      - run:
          name: Create Package
          command: |
            ./build/sfdx/login.sh -l https://login.salesforce.com -c $SFDC_CLIENT_ID -u $SFDC_USER
            # Create unlocked package version